ci:
  autoupdate_schedule: quarterly
  autoupdate_branch: 'trunk'
  autofix_prs: false
  # rust does not work on pre-commit.ci
  skip: [fmt, check, clippy]

default_language_version:
  rust: 1.81.0

repos:
- repo: https://github.com/backplane/pre-commit-rust-hooks
  rev: v1.1.0
  hooks:
  - id: fmt
  - id: check
  - id: clippy
    args:
      - --all-targets
      - --all-features
      - --
      - -Dwarnings
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.6.0'
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-toml
  - id: check-case-conflict
  - id: mixed-line-ending
- repo: https://github.com/crate-ci/typos
  rev: v1.22.9
  hooks:
    - id: typos
